### ISSUE TITLE
Should all features be normalized?

### ISSUE THREAD

**Issue by andreahorbach** [ltl-ude/escrito#15]
Some algorithms benefit from normalization. Should the normalization step be executed in every single feature extractor or rather as one preprocessing step before classification? I would be in favor of the latter because:
- if users write their own feature extractors, the normalization makes it much more complicated (Metacollector), and they may not know that they have to do it.
- feature extractor results are much more meaningful/human readable if not normalized

**Comment by zesch** [comment]
I am not sure human readability is the main goal in feature extraction ;)

If users write non-normalized features, it is their problem.
However, I think all the features we already provide with the framework should be normalized.

@Horsmann any thoughts on this?

**Comment by Horsmann** [comment]
The backend should not provide features that might become problematic. If the user decides to implement such features it is their own :)

**Comment by andreahorbach** [comment]
final outcome: it would be good if they did, but this is for now not a top priority
