### ISSUE TITLE
Sort out which ASAP essay reader to use

### ISSUE THREAD

**Issue by andreahorbach** [ltl-ude/escrito#41]
We currently have two versions for the asap essay dataset: one based on tsv files and one based on xml. @zesch It looks to me as if the tsv reader is the more official one corresponding to the released data and the xml reader was only for internal use?

**Comment by zesch** [comment]
Do we even have an XML-based version of the data?
Is this version ever used somewhere?
If not, we can probably drop it.

**Comment by andreahorbach** [comment]
I never used the xml-version, but that was old code, so I wanted to check before just dropping it. But then it seems like we don't need it.
