### ISSUE TITLE
Integrate old length features from tc 0.9

### ISSUE THREAD

**Issue by andreahorbach** [ltl-ude/escrito#5]
they do not exist anymore in tc 1.0.0, we used them quite regularly

**Comment by zesch** [comment]
@Horsmann where are they now?

**Comment by Horsmann** [comment]
The token ratio (normalized) is called `TokenRatioPerDocument`. The absolute value version has been deleted. TC shouldn't endorse using problematic features that are subject to numeric stability issues.

**Comment by andreahorbach** [comment]
added with a16de79

**Comment by andreahorbach** [comment]
Whether all features should be normalized to. range between 0 and 1 (or -1 and +1) will become a separate issue
